version: '3'
services:
  htcollector:
    image: ghcr.io/varkenvarken/htcollector:latest
    ports:
      - 8083:1883
    env_file: .env
    environment:
      - DBSERVER=dbserver
      - DBPORT=3306
      - PORT=1883
    depends_on:
      dbserver:
        condition: service_healthy
    networks:
      - service_network
  dbserver:
    image: ghcr.io/varkenvarken/mariadb:latest
    ports:
      - 3366:3306
    env_file: .env
    volumes:
      - htcollector_data:/var/lib/mysql
    networks:
      - service_network
networks:
  service_network:
volumes:
  htcollector_data:
