version: '3'
services:
  htcollector:
    image: varkenvarken/htcollector:latest
    ports:
      - 8083:1883
    env_file: .env
    environment:
      - DBSERVER=dbserver
      - DBPORT=3306
      - PORT=1883
    depends_on:
      dbserver:
        condition: service_healthy
    networks:
      - service_network
  dbserver:
    image: varkenvarken/mariadb:latest
    ports:
      - 3306:3306
    env_file: .env
    networks:
      - service_network
networks:
  service_network:
