name: "Test"

on:
  push:
    branches:
      - master 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install binary dependencies
        run: |
          wget https://downloads.mariadb.com/MariaDB/mariadb_repo_setup
          chmod +x mariadb_repo_setup
          ./mariadb_repo_setup    --mariadb-server-version="mariadb-10.6"
          apt install libmariadb3 libmariadb-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions mariadb
      - name: Test with tox
        run: tox